id: 5550afdb8ff84131b52a97b474dce290
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_286-The_Dedication_Protecting_All_Beings-v2
  language: bo
  author: ''
  volume: {}
